export const ASTRON_SOURCE = "ASTRON_SOURCE";
export const MODELS = {
    ADMIN:"ADMIN_MODEL",
    ABOUT:"ABOUT_MODEL",
    CONTACT:"CONTACT_MODEL",
    COURSES:"COURSES_MODEL",
    TEACHERS:"TEACHERS_MODEL"
};